defmodule BlogWeb.PageController do
  @moduledoc """
  Legacy page controller (currently unused).

  This controller was generated by Phoenix authentication generator.
  It is not wired into the router and serves no purpose in the current app.

  ## Why Unused?

  The app uses LiveView-based pages instead of traditional controllers:
  - HomeLive (home page)
  - FeedLive (post feed)
  - PostLive.Show (single post)
  - UserLive.* (auth pages)

  LiveView provides:
  - Server-rendered interactivity (no page reload)
  - Real-time updates via WebSocket
  - Stateful UI management
  - Better developer experience

  Traditional controllers return static HTML without state management.

  ## Potential Uses

  Could be repurposed for:
  - Static pages (terms, privacy, about)
  - API endpoints (if building REST API)
  - Server-rendered non-interactive pages

  But currently not needed due to LiveView architecture.

  ## Cleanup Opportunity

  This file is safe to delete if:
  - No plans to use traditional page controllers
  - All content moved to LiveViews
  - API routes not planned

  For now, left as-is (may be useful as reference for future developers).
  """

  use BlogWeb, :controller

  def home(conn, _params) do
    render(conn, :home)
  end
end
